gitRepo:
  gitProvider: git_test_go
  path: complexmathguy/go-demo
  DockerUserName: tylertravismya
  DockerPassword: 69cutlass
  DockerOrgName: theharbormaster
  DockerRepo: go-demo
  DockerHost: 
  DockerTag: latest
